---
abstract: 'fake autoboxing (call methods on plain scalars)'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fauxtobox
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/mauke/Fauxtobox.git
version: 0.01
