---
abstract: 'fake autoboxing (call methods on plain scalars)'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
  strict: '0'
  warnings: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Fauxtobox
no_index:
  directory:
    - t
    - inc
requires:
  Data::Munge: '0.05'
  Exporter: '0'
  Scalar::Util: '0'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/mauke/Fauxtobox.git
version: '0.02'
